import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import ganache from 'ganache';
import solc from 'solc';
import {JsonRpcProvider,ContractFactory,Contract,HDNodeWallet,parseEther,Wallet} from '../demo/deps.mjs';
import {DEV_MNEMONIC} from '../demo/dev.mjs';
import {compile} from '../demo/compile.mjs';
import {verifyDeployment,allowedChain} from '../../testnet/verify.mjs';
import {DurableWitness} from '../../witness/durable.mjs';
import {Journal} from '../../witness/journal.mjs';
import {readChain} from '../../witness/read-chain.mjs';
import {evaluate} from '../../witness/model.mjs';
import {finalityBlock} from '../../witness/finality.mjs';
import {serveTestnet} from '../../testnet/server.mjs';
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'lorrow-testnet-'));
const a=compile({includeSources:true});
let count=0;const pass=name=>console.log(`TESTNET PASS ${++count}: ${name}`);
const chain=ganache.server({logging:{quiet:true},wallet:{mnemonic:DEV_MNEMONIC},chain:{chainId:31337,hardfork:'shanghai'},miner:{timestampIncrement:0}});
await chain.listen(0,'127.0.0.1');const provider=new JsonRpcProvider(`http://127.0.0.1:${chain.address().port}`,undefined,{cacheTimeout:-1});provider.pollingInterval=20;
const [borrower,lender]=await Promise.all([provider.getSigner(1),provider.getSigner(2)]);
const wallets=[4,5,6].map(i=>HDNodeWallet.fromPhrase(DEV_MNEMONIC,undefined,`m/44'/60'/0'/0/${i}`));
const witnesses=wallets.map(w=>w.address).sort((a,b)=>BigInt(a)<BigInt(b)?-1:1);
const mine=async()=>{for(let i=0;i<3;i++)await provider.send('evm_mine',[]);};
const tx=async p=>{await(await p).wait();};
let signer,site;
try {
 const roundtrip=JSON.parse(solc.compile(JSON.stringify(a.standardInput)));
 assert.equal(roundtrip.contracts['src/FixedTermLoan.sol'].FixedTermLoan.evm.bytecode.object,a.loan.evm.bytecode.object);
 assert.equal(roundtrip.contracts['src/LorrowEscrow.sol'].LorrowEscrow.evm.bytecode.object,a.vault.evm.bytecode.object);
 pass('exported standard JSON input recompiles to identical constructor bytecode');
 const block=await provider.getBlock('latest');const terms={lender:await lender.getAddress(),principal:parseEther('0.001').toString(),interest:parseEther('0.0001').toString(),duration:'30',grace:'10',fundingDeadline:String(block.timestamp+500),exitDelay:'10',approvalThreshold:'2',vetoThreshold:'1'};
 const loan=await new ContractFactory(a.loan.abi,a.loan.evm.bytecode.object,borrower).deploy(terms,witnesses);await loan.waitForDeployment();
 const opened=await loan.openVault({value:parseEther('0.003')});await opened.wait();
 const manifest={chainId:31337,borrower:await borrower.getAddress(),terms,witnesses,loan:await loan.getAddress(),vault:await loan.vault(),collateral:parseEther('0.003').toString(),creationTxHash:loan.deploymentTransaction().hash,openTxHash:opened.hash};
 let report=await verifyDeployment(provider,a,manifest,{allowLocal:true});assert.equal(report.config.vault,manifest.vault);
 for(const bad of [{...manifest,vault:await lender.getAddress()},{...manifest,borrower:await lender.getAddress()},{...manifest,terms:{...terms,interest:'1'}},{...manifest,collateral:'1'}])await assert.rejects(verifyDeployment(provider,a,bad,{allowLocal:true}));
 const changed=new Proxy(provider,{get(target,key){if(key==='getCode')return async()=> '0x00';const v=target[key];return typeof v==='function'?v.bind(target):v;}});
 await assert.rejects(verifyDeployment(changed,a,manifest,{allowLocal:true}),/runtime/);
 assert.throws(()=>allowedChain(1),/Sepolia/);await assert.rejects(verifyDeployment(provider,a,manifest),/Sepolia/);
 pass('constructor, borrower, opening value, vault and full immutable runtime verification; wrong chain/code refused');
 await assert.rejects(finalityBlock({getBlock:async()=>null}),/finalized/);
 await assert.rejects(finalityBlock(provider,{tag:'latest'}),/Finalized/);
 await assert.rejects(finalityBlock(provider,{confirmations:2}),/Finalized/);
 const finality={confirmations:2};await mine();
 await tx(loan.connect(lender).fund({value:terms.principal}));await tx(loan.repay({value:BigInt(terms.principal)+BigInt(terms.interest)}));
 const file=path.join(temp,'witness.jsonl'),settings={provider,artifacts:a,manifest,wallet:wallets[0],journal:file,allowLocal:true,finality};
 signer=new DurableWitness(settings);
 async function request(){const s=await readChain(provider,a,report.config),m=evaluate(s,report.config);return {type:'approve',chainId:31337,loan:manifest.loan,vault:manifest.vault,proposal:{nonce:String(s.nonce+1n),lenderAmount:String(m.lenderAmount),stateHash:m.stateHash,deadline:String(s.timestamp+3600n)}};}
 const req=await request();await assert.rejects(signer.sign(req),/finalized/);assert.equal(signer.journal.records.length,0);
 await mine();const signed=await signer.sign(req);assert.equal(signer.journal.records.length,1);assert(fs.readFileSync(file,'utf8').endsWith('\n'));
 pass('unfinalized repayment refuses signing; selected confirmation blocks permit independently checked authorization');
 assert.throws(()=>new Journal(file,wallets[0].address),/live writer/);
 signer.close();signer=new DurableWitness(settings);const replay=await signer.sign(req);assert.equal(replay.signature,signed.signature);assert.equal(signer.journal.records.length,1);
 await assert.rejects(signer.sign({...req,proposal:{...req.proposal,lenderAmount:'1'}}),/payout/);
 await assert.rejects(signer.sign({...req,proposal:{...req.proposal,deadline:String(BigInt(req.proposal.deadline)+1n)}}),/expire/);
 assert.equal(signer.journal.records.length,1);
 pass('restart replays the durable signature; live writer, payout changes and premature deadline renewal refused');
 await provider.send('evm_setTime',[(Number(req.proposal.deadline)+1)*1000]);await mine();
 const renewal=await signer.sign(await request());assert.equal(signer.journal.records.length,2);assert.notEqual(renewal.digest,signed.digest);
 pass('same-allocation deadline renewal allowed only after prior expiry in finalized time');
 const second=new DurableWitness({...settings,wallet:wallets[1],journal:path.join(temp,'second.jsonl')});
 const renewedRequest=await request();let other;
 try{other=await second.sign(renewedRequest);}finally{second.close();}
 const signatures=[renewal,other].sort((a,b)=>BigInt(a.address)<BigInt(b.address)?-1:1).map(r=>r.signature);
 const vault=new Contract(manifest.vault,a.vault.abi,borrower);
 await tx(vault.queueSettlement(renewedRequest.proposal.lenderAmount,renewedRequest.proposal.deadline,signatures));
 const vetoRequest={type:'veto',chainId:31337,loan:manifest.loan,vault:manifest.vault,nonce:'1',reason:'operator_cancel'};
 const cancel=await signer.sign(vetoRequest);await tx(vault.veto([cancel.signature]));
 await assert.rejects(signer.sign(await request()),/finaliz/);await mine();
 const fresh=await signer.sign(await request());assert.equal(fresh.nonce,'2');
 pass('durable current-state veto cancels without allocation; new approval waits for finalized cancellation/nonce');
 const crash=path.join(temp,'crash.jsonl'),fixture=path.join(temp,'record.json');fs.writeFileSync(fixture,JSON.stringify(signed));
 const child=spawnSync(process.execPath,[fileURLToPath(new URL('./journal-crash.mjs',import.meta.url)),crash,fixture],{encoding:'utf8'});assert.equal(child.status,0,child.stderr);
 const recovered=new Journal(crash,wallets[0].address);assert.equal(recovered.records[0].signature,signed.signature);recovered.close();
 const broken=path.join(temp,'broken.jsonl');fs.writeFileSync(broken,fs.readFileSync(file,'utf8').slice(0,-4));assert.throws(()=>new Journal(broken,wallets[0].address),/Incomplete/);
 const edited=path.join(temp,'edited.jsonl');fs.writeFileSync(edited,fs.readFileSync(file,'utf8').replace('"lenderAmount":"0"','"lenderAmount":"1"'));assert.throws(()=>new Journal(edited,wallets[0].address),/mismatch/);
 pass('abrupt writer death recovers its lock and signature; incomplete/tampered journals fail closed');
 const encrypted=await wallets[0].encrypt('test-password-not-a-real-secret');assert(!encrypted.includes(wallets[0].privateKey));
 assert.equal((await Wallet.fromEncryptedJson(encrypted,'test-password-not-a-real-secret')).address,wallets[0].address);
 pass('encrypted keystore roundtrip preserves the signing identity without plaintext private key storage');
 signer.close();signer=null;site=await serveTestnet({port:0,directory:path.join(temp,'site')});
 const page=await fetch(site.url);assert.equal(page.status,200);assert.match(await page.text(),/Sepolia/);
 const dep=await fetch(site.url+'/contracts/demo/deps.mjs');assert.match(await dep.text(),/vendor\/ethers/);
 const vendor=await fetch(site.url+'/vendor/ethers.js');assert.equal(vendor.status,200);
 const post=await fetch(site.url,{method:'POST',body:'anything'});assert.equal(post.status,405);
 const key=await fetch(site.url+'/../keys/witness-1.json');assert.equal(key.status,404);
 pass('static wallet interface build serves its pinned dependency, rejects writes, and exposes no keystores');
 console.log(`Complete: ${count} testnet preparation scenario groups passed.`);
}finally{signer?.close();await site?.close();provider.destroy();await chain.close();fs.rmSync(temp,{recursive:true,force:true});}
